version: '3.7'
services:
  sarndbox-nvidia:
    build:
      context: .
      args:
        - "DISPLAY=unix${DISPLAY}"
        - "DRIVER_URL=https://http.download.nvidia.com/XFree86/Linux-x86_64/${NVIDIA_VERSION}/NVIDIA-Linux-x86_64-${NVIDIA_VERSION}.run"
      target: "nvidia"
    network_mode: "host"
    privileged: true
    environment:
      - "VRUI_VERSION=Vrui-8.0-002"
      - "DISPLAY=unix${DISPLAY}"
    runtime: nvidia
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/dev/dri:/dev/dri"
      - "${PWD}/Kinect:/usr/local/etc/Vrui-8.0/Kinect-3.10/"
      - "${PWD}/config:/root/config"
  sarndbox:
    build:
      context: .
      args:
        - "DISPLAY=unix${DISPLAY}"
      target: "base"
    network_mode: "host"
    privileged: true
    environment:
      - "VRUI_VERSION=Vrui-8.0-002"
      - "DISPLAY=unix${DISPLAY}"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/dev/dri:/dev/dri"
      - "${PWD}/Kinect:/usr/local/etc/Vrui-8.0/Kinect-3.10/"
      - "${PWD}/config:/root/config"
