version: '3.7'
services:
  sarndbox:
    build:
      context: .
      args:
        - "DISPLAY=${DISPLAY}"
    network_mode: "host"
    privileged: true
    environment:
      - "VRUI_VERSION=Vrui-8.0-002"
    runtime: nvidia
    volumes:
      - "${PWD}/teste:/data"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "${HOME}/.Xauthority:/root/.Xauthority:Z"
      - "/dev/dri:/dev/dri"
      - "${PWD}/Kinect:/usr/local/etc/Vrui-8.0/Kinect-3.10/"
        #    devices:
        #- "/dev/kinect/audio:/dev/kinect/audio"
        #- "/dev/kinect/camera:/dev/kinect/camera"
        #- "/dev/kinect/motor:/dev/kinect/motor"
        #    deploy:
        #      resources:
        #        reservations:
        #          devices:
        #            - capabilities: [gpu]
